## Name:  Muhammad Mubashir Shafique 
## Student ID: 
## Section: G
## GitHub: https://github.com/MubashirShafique
## Kaggle: https://www.kaggle.com/mubashir24
## Dataset: Stroke Prediction Dataset (Kaggle) 
## Dataset Source: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction dataset

In [21]:
import pandas as pd 
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("healthcare-dataset-stroke-data_1.csv")

In [3]:
df.shape

(5110, 12)

In [4]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [5]:
df["gender"].value_counts()

gender
Female    2994
Male      2115
Other        1
Name: count, dtype: int64

In [6]:
df["stroke"].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

In [7]:
df[df["stroke"] == 1]["gender"].value_counts()

gender
Female    141
Male      108
Name: count, dtype: int64

In [8]:
df[df["stroke"] == 0]["gender"].value_counts()

gender
Female    2853
Male      2007
Other        1
Name: count, dtype: int64

In [9]:
df["stroke"].value_counts(normalize=True) * 100

stroke
0    95.127202
1     4.872798
Name: proportion, dtype: float64

In [10]:
# Clean the data
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [11]:
df.drop(columns=["id"],inplace=True)

In [12]:
df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [13]:
df[df["gender"]== "Other"]

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
3116,Other,26.0,0,0,No,Private,Rural,143.33,22.4,formerly smoked,0

In [14]:
df.drop(index=3116, inplace=True)

In [15]:
df["gender"].value_counts()

gender
Female    2994
Male      2115
Name: count, dtype: int64

In [16]:
encoded_df = pd.get_dummies(df, columns=['gender','ever_married','work_type','Residence_type','smoking_status'],dtype=int)

In [17]:
encoded_df.head()

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,ever_married_No,ever_married_Yes,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,67.0,0,1,228.69,36.6,1,0,1,0,1,...,0,1,0,0,0,1,0,1,0,0
1,61.0,0,0,202.21,NaN,1,1,0,0,1,...,0,0,1,0,1,0,0,0,1,0
2,80.0,0,1,105.92,32.5,1,0,1,0,1,...,0,1,0,0,1,0,0,0,1,0
3,49.0,0,0,171.23,34.4,1,1,0,0,1,...,0,1,0,0,0,1,0,0,0,1
4,79.0,1,0,174.12,24.0,1,1,0,0,1,...,0,0,1,0,1,0,0,0,1,0

In [19]:
X=df.drop(columns=["stroke"])
Y=df["stroke"]

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=30,stratify=Y)

gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
dtype: int64